/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Member
         * @description Return the profile header and goals for a member.
         *
         *     Reads the Member Context graph (KG 2). When Neo4j is unreachable or the
         *     graph has not been built yet, falls back to the ``member-context.json``
         *     seed file so the dashboard stays usable before/without ingest.
         *
         *     Args:
         *         member_id: Member identifier, e.g. ``mbr_01HX9JORDAN``.
         *         request: Current request; carries the app-lifetime Neo4j driver.
         *
         *     Returns:
         *         MemberResponse with the member's profile fields and goals.
         *
         *     Raises:
         *         HTTPException: 404 if ``member_id`` does not match a known member;
         *             500 if neither the graph nor the seed file can serve it.
         */
        get: operations["get_member_api_members__member_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workout
         * @description Generate (or adjust) a workout plan for a member.
         *
         *     Send the previous response's ``constraints_used`` back as
         *     ``prior_constraints`` together with a follow-up message to adjust the
         *     plan — the constraint set merges and the safety traversal re-runs.
         *
         *     Raises:
         *         HTTPException: 503 when Neo4j or the model API is unavailable, 422
         *             when the constraints leave an empty exercise pool, 500 otherwise.
         */
        post: operations["create_workout_api_workout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report API liveness and Neo4j connectivity.
         *
         *     Returns:
         *         HealthResponse with ``status`` "ok" when Neo4j is reachable,
         *         "degraded" otherwise.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Alternative
         * @description A feasible, safe substitute for an excluded exercise.
         */
        Alternative: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /** Shared Patterns */
            shared_patterns: string[];
            /** Shared Muscle Groups */
            shared_muscle_groups: string[];
        };
        /**
         * ConstraintSet
         * @description The merged, serializable constraint state for one conversation.
         *
         *     Returned on every plan as ``constraints_used``; send it back as
         *     ``prior_constraints`` with a follow-up message to adjust the plan.
         */
        ConstraintSet: {
            /** Equipment Ids */
            equipment_ids?: string[] | null;
            /** Injuries */
            injuries?: components["schemas"]["InjuryConstraint"][];
            /** Exclude Concept Ids */
            exclude_concept_ids?: string[];
            /** Downrank Concept Ids */
            downrank_concept_ids?: string[];
            /** Notes */
            notes?: string[];
        };
        /**
         * ExcludedExercise
         * @description An exercise removed by a filter, with why and what to do instead.
         */
        ExcludedExercise: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "explicit" | "equipment" | "safety";
            /** Reason */
            reason: string;
            /** Missing Equipment */
            missing_equipment?: string[];
            /** Fired Rules */
            fired_rules?: components["schemas"]["RuleFiring"][];
            path?: components["schemas"]["GraphPath"] | null;
            /** Alternatives */
            alternatives?: components["schemas"]["Alternative"][];
        };
        /**
         * Goal
         * @description A member's coaching goal.
         */
        Goal: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Priority */
            priority: number;
            /** Target Date */
            target_date: string | null;
        };
        /**
         * GraphPath
         * @description A walked path plus the query that reproduces it (PROV-O ``GraphPath``).
         */
        GraphPath: {
            /** Nodes */
            nodes: string[];
            /** Description */
            description: string;
            /** Cypher */
            cypher: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check result for the API and its Neo4j dependency.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Neo4J */
            neo4j: string;
        };
        /**
         * InjuryConstraint
         * @description One active injury, already resolved to a Condition concept.
         */
        InjuryConstraint: {
            /** Condition Id */
            condition_id: string;
            /**
             * Status
             * @default recovering
             * @enum {string}
             */
            status: "acute" | "recovering" | "resolved";
            /**
             * Severity
             * @default mild
             * @enum {string}
             */
            severity: "mild" | "moderate" | "severe";
        };
        /**
         * MemberProfile
         * @description Profile-header fields for the member view.
         */
        MemberProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** Sex */
            sex: string;
            /** Tier */
            tier: string;
            /**
             * Member Since
             * Format: date
             */
            member_since: string;
            /** Coach Id */
            coach_id: string;
            /** Timezone */
            timezone: string;
        };
        /**
         * MemberResponse
         * @description Member context served to the dashboard: profile header plus goals.
         */
        MemberResponse: {
            profile: components["schemas"]["MemberProfile"];
            /** Goals */
            goals: components["schemas"]["Goal"][];
        };
        /** PlanSection */
        PlanSection: {
            /** Title */
            title: string;
            /** Exercises */
            exercises: components["schemas"]["PlannedExercise"][];
        };
        /**
         * PlannedExercise
         * @description One line of the plan, with the graph's justification attached.
         */
        PlannedExercise: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /** Sets */
            sets: number;
            /** Reps */
            reps?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Rest Seconds */
            rest_seconds: number;
            /** Coach Note */
            coach_note?: string | null;
            /** Estimated Seconds */
            estimated_seconds: number;
            /** Why Chosen */
            why_chosen: string;
            /** Fired Rules */
            fired_rules?: components["schemas"]["RuleFiring"][];
            /** Pool Notes */
            pool_notes?: string[];
        };
        /**
         * RuleFiring
         * @description One safety rule that fired for one exercise.
         */
        RuleFiring: {
            /** Rule Id */
            rule_id: string;
            /** Condition Id */
            condition_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "exclude" | "downrank" | "promote" | "allow";
            /** Priority */
            priority: number;
            /**
             * Score Delta
             * @default 0
             */
            score_delta: number;
            /** Rationale */
            rationale: string;
            /** Escalated From */
            escalated_from?: string | null;
            anatomy_path?: components["schemas"]["GraphPath"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkoutPlan
         * @description The typed response of ``POST /api/workout`` (doubles as the schema).
         */
        WorkoutPlan: {
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            warmup: components["schemas"]["PlanSection"];
            main: components["schemas"]["PlanSection"];
            cooldown: components["schemas"]["PlanSection"];
            /** Time Window Minutes */
            time_window_minutes: number;
            /** Estimated Duration Minutes */
            estimated_duration_minutes: number;
            /** Filtered Out For Safety */
            filtered_out_for_safety: components["schemas"]["ExcludedExercise"][];
            /** Other Exclusions */
            other_exclusions: components["schemas"]["ExcludedExercise"][];
            constraints_used: components["schemas"]["ConstraintSet"];
            /** Resolution Notes */
            resolution_notes: string[];
            /** Pool Size */
            pool_size: number;
        };
        /**
         * WorkoutRequest
         * @description Input to ``POST /api/workout``.
         */
        WorkoutRequest: {
            /** Member Id */
            member_id: string;
            /** Prompt */
            prompt: string;
            /** Time Window Minutes */
            time_window_minutes: number;
            prior_constraints?: components["schemas"]["ConstraintSet"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_member_api_members__member_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_api_workout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
