/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Member
         * @description Return the profile header and goals for a member.
         *
         *     Reads the Member Context graph (KG 2). When Neo4j is unreachable or the
         *     graph has not been built yet, falls back to the ``member-context.json``
         *     seed file so the dashboard stays usable before/without ingest.
         *
         *     Args:
         *         member_id: Member identifier, e.g. ``mbr_01HX9JORDAN``.
         *         request: Current request; carries the app-lifetime Neo4j driver.
         *
         *     Returns:
         *         MemberResponse with the member's profile fields and goals.
         *
         *     Raises:
         *         HTTPException: 404 if ``member_id`` does not match a known member;
         *             500 if neither the graph nor the seed file can serve it.
         */
        get: operations["get_member_api_members__member_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Workout
         * @description Generate (or adjust) a workout plan for a member.
         *
         *     Send the previous response's ``constraints_used`` back as
         *     ``prior_constraints`` together with a follow-up message to adjust the
         *     plan — the constraint set merges and the safety traversal re-runs.
         *
         *     Raises:
         *         HTTPException: 503 when Neo4j or the model API is unavailable, 422
         *             when the constraints leave an empty exercise pool, 500 otherwise.
         */
        post: operations["create_workout_api_workout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{member_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Member Context Slice
         * @description Read sections of the member-context graph directly (no LLM).
         *
         *     Backs the copilot panel's morning-brief and chat-history surfaces — the
         *     same retrieval the agent's ``member_context`` tool uses.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown member, 503 when Neo4j is down.
         */
        get: operations["member_context_slice_api_members__member_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/copilot/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copilot Run
         * @description Run one copilot turn for a member, streaming AG-UI events back.
         *
         *     Raises:
         *         HTTPException: 503 when the model API key or Neo4j is unavailable.
         */
        post: operations["copilot_run_api_copilot__member_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Traces
         * @description List recent traces, newest first.
         *
         *     Args:
         *         request: The incoming request.
         *         limit: Maximum traces to return.
         *         status: Optional filter on whether the trace contains a failed span.
         *
         *     Returns:
         *         Trace summaries with span counts, token usage, and cost.
         *
         *     Raises:
         *         HTTPException: 503 when tracing is disabled or the store is unreachable.
         */
        get: operations["list_traces_api_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trace Stats
         * @description Summarise recent tracing activity.
         *
         *     Args:
         *         request: The incoming request.
         *         window_hours: How far back to aggregate, up to one week.
         *
         *     Returns:
         *         Counts, token and cost totals, and latency percentiles.
         *
         *     Raises:
         *         HTTPException: 503 when tracing is disabled or the store is unreachable.
         */
        get: operations["trace_stats_api_traces_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace
         * @description Fetch one trace and every span inside it.
         *
         *     Args:
         *         request: The incoming request.
         *         trace_id: The 32-character hex trace id.
         *
         *     Returns:
         *         The trace summary plus its spans, ordered by start time.
         *
         *     Raises:
         *         HTTPException: 404 when no such trace is stored, 503 when tracing is
         *             disabled or the store is unreachable.
         */
        get: operations["get_trace_api_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report API liveness, Neo4j connectivity, and what the graph holds.
         *
         *     The startup banner (`make up`) reads this to decide when the stack is
         *     actually serving and whether the AI features are configured.
         *
         *     Returns:
         *         HealthResponse with ``status`` "ok" when Neo4j is reachable and the
         *         graph is loaded, "degraded" otherwise. Counts are 0 when degraded.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdherenceSlice */
        AdherenceSlice: {
            /** Trend */
            trend: string;
            /** Weeks */
            weeks: {
                [key: string]: string | number;
            }[];
        };
        /**
         * Alternative
         * @description A feasible, safe substitute for an excluded exercise.
         */
        Alternative: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /** Shared Patterns */
            shared_patterns: string[];
            /** Shared Muscle Groups */
            shared_muscle_groups: string[];
        };
        /** BiomarkerSlice */
        BiomarkerSlice: {
            /** Resting Hr Bpm */
            resting_hr_bpm: number;
            /** Hrv Ms */
            hrv_ms: number;
            /** Sleep Hours Last 7 Days */
            sleep_hours_last_7_days: number[];
        };
        /** CoachBriefSlice */
        CoachBriefSlice: {
            /** Generated For */
            generated_for: string;
            /** Churn Risk Level */
            churn_risk_level: string;
            /** Churn Risk Reasons */
            churn_risk_reasons: string[];
            /** Tasks */
            tasks: {
                [key: string]: string;
            }[];
        };
        /**
         * ConstraintSet
         * @description The merged, serializable constraint state for one conversation.
         *
         *     Pure state: the ids and flags the traversal acts on, and nothing else.
         *     Returned on every plan as ``constraints_used``; send it back as
         *     ``prior_constraints`` with a follow-up message to adjust the plan.
         *
         *     The prose explaining *how* this set was derived is deliberately not here
         *     — it belongs to a single response, not to the carried-forward state, and
         *     lives on ``WorkoutPlan.resolution_notes``.
         */
        ConstraintSet: {
            /** Equipment Ids */
            equipment_ids?: string[] | null;
            /** Injuries */
            injuries?: components["schemas"]["InjuryConstraint"][];
            /** Exclude Concept Ids */
            exclude_concept_ids?: string[];
            /** Downrank Concept Ids */
            downrank_concept_ids?: string[];
        };
        /**
         * ContextSlice
         * @description The member-context data returned to the agent, one field per section.
         */
        ContextSlice: {
            /** Member Id */
            member_id: string;
            /**
             * Now Anchor
             * @description The dataset's 'today'. All recency/trend statements must be computed against this date, never the wall clock.
             */
            now_anchor: string;
            /** Profile */
            profile?: {
                [key: string]: string | number;
            } | null;
            /** Goals */
            goals?: {
                [key: string]: string | number | null;
            }[] | null;
            adherence?: components["schemas"]["AdherenceSlice"] | null;
            biomarkers?: components["schemas"]["BiomarkerSlice"] | null;
            /** Weight Trend */
            weight_trend?: {
                [key: string]: string | number;
            }[] | null;
            /** Labs */
            labs?: components["schemas"]["LabPanelSlice"][] | null;
            /** Workout History */
            workout_history?: {
                [key: string]: string | number | boolean | string[] | null;
            }[] | null;
            /** Chat History */
            chat_history?: {
                [key: string]: string | boolean | string[] | null;
            }[] | null;
            coach_brief?: components["schemas"]["CoachBriefSlice"] | null;
            /** Injuries */
            injuries?: {
                [key: string]: string | null;
            }[] | null;
            /** Equipment */
            equipment?: string[] | null;
        };
        /**
         * ExcludedExercise
         * @description An exercise removed by a filter, with why and what to do instead.
         */
        ExcludedExercise: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "explicit" | "equipment" | "safety";
            /** Reason */
            reason: string;
            /** Missing Equipment */
            missing_equipment?: string[];
            /** Fired Rules */
            fired_rules?: components["schemas"]["RuleFiring"][];
            path?: components["schemas"]["GraphPath"] | null;
            /** Alternatives */
            alternatives?: components["schemas"]["Alternative"][];
        };
        /**
         * Goal
         * @description A member's coaching goal.
         */
        Goal: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Priority */
            priority: number;
            /** Target Date */
            target_date: string | null;
        };
        /**
         * GraphPath
         * @description A walked path plus the query that reproduces it (PROV-O ``GraphPath``).
         */
        GraphPath: {
            /** Nodes */
            nodes: string[];
            /** Description */
            description: string;
            /** Cypher */
            cypher: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Health check result for the API and its Neo4j dependency.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Neo4J */
            neo4j: string;
            /** Ai Enabled */
            ai_enabled: boolean;
            /** Model */
            model: string;
            /** Exercises */
            exercises: number;
            /** Members */
            members: number;
            /** Tracing Enabled */
            tracing_enabled: boolean;
            /** Traces Recorded */
            traces_recorded: number;
        };
        /**
         * InjuryConstraint
         * @description One active injury, already resolved to a Condition concept.
         */
        InjuryConstraint: {
            /** Condition Id */
            condition_id: string;
            /**
             * Status
             * @default recovering
             * @enum {string}
             */
            status: "acute" | "recovering" | "resolved";
            /**
             * Severity
             * @default mild
             * @enum {string}
             */
            severity: "mild" | "moderate" | "severe";
        };
        /** LabPanelSlice */
        LabPanelSlice: {
            /** Panel Type */
            panel_type: string;
            /** Date */
            date: string;
            /** Results */
            results: {
                [key: string]: number;
            };
        };
        /**
         * MemberProfile
         * @description Profile-header fields for the member view.
         */
        MemberProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Age */
            age: number;
            /** Sex */
            sex: string;
            /** Tier */
            tier: string;
            /**
             * Member Since
             * Format: date
             */
            member_since: string;
            /** Coach Id */
            coach_id: string;
            /** Timezone */
            timezone: string;
        };
        /**
         * MemberResponse
         * @description Member context served to the dashboard: profile header plus goals.
         */
        MemberResponse: {
            profile: components["schemas"]["MemberProfile"];
            /** Goals */
            goals: components["schemas"]["Goal"][];
        };
        /** PlanSection */
        PlanSection: {
            /** Title */
            title: string;
            /** Exercises */
            exercises: components["schemas"]["PlannedExercise"][];
        };
        /**
         * PlannedExercise
         * @description One line of the plan, with the graph's justification attached.
         */
        PlannedExercise: {
            /** Exercise Id */
            exercise_id: string;
            /** Name */
            name: string;
            /** Sets */
            sets: number;
            /** Reps */
            reps?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /** Rest Seconds */
            rest_seconds: number;
            /** Coach Note */
            coach_note?: string | null;
            /** Estimated Seconds */
            estimated_seconds: number;
            /** Why Chosen */
            why_chosen: string;
            /** Fired Rules */
            fired_rules?: components["schemas"]["RuleFiring"][];
            /** Pool Notes */
            pool_notes?: string[];
        };
        /**
         * RuleFiring
         * @description One safety rule that fired for one exercise.
         */
        RuleFiring: {
            /** Rule Id */
            rule_id: string;
            /** Condition Id */
            condition_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "exclude" | "downrank" | "promote" | "allow";
            /** Priority */
            priority: number;
            /**
             * Score Delta
             * @default 0
             */
            score_delta: number;
            /** Rationale */
            rationale: string;
            /** Escalated From */
            escalated_from?: string | null;
            anatomy_path?: components["schemas"]["GraphPath"] | null;
        };
        /**
         * SpanCategory
         * @description What kind of work a span represents, in the app's own vocabulary.
         * @enum {string}
         */
        SpanCategory: "agent" | "llm" | "tool" | "db" | "http" | "other";
        /**
         * SpanStatus
         * @description Outcome of a span, flattened from OpenTelemetry's status code.
         * @enum {string}
         */
        SpanStatus: "ok" | "error" | "unset";
        /**
         * TraceDetail
         * @description A trace summary plus every span in it, ordered by start time.
         */
        TraceDetail: {
            summary: components["schemas"]["TraceSummary"];
            /** Spans */
            spans: components["schemas"]["TraceSpan"][];
        };
        /**
         * TraceSpan
         * @description One span as the trace detail view shows it.
         */
        TraceSpan: {
            /** Span Id */
            span_id: string;
            /** Parent Span Id */
            parent_span_id: string | null;
            /** Name */
            name: string;
            category: components["schemas"]["SpanCategory"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
            status: components["schemas"]["SpanStatus"];
            /** Error Message */
            error_message: string | null;
            /** Model */
            model: string | null;
            /** Tool Name */
            tool_name: string | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Micro Usd */
            cost_micro_usd: number;
            /** Input Preview */
            input_preview: string | null;
            /** Output Preview */
            output_preview: string | null;
            /** Input Truncated */
            input_truncated: boolean;
            /** Output Truncated */
            output_truncated: boolean;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
        };
        /**
         * TraceStats
         * @description Aggregate figures over a recent window, for the traces page header.
         */
        TraceStats: {
            /** Window Hours */
            window_hours: number;
            /** Trace Count */
            trace_count: number;
            /** Error Trace Count */
            error_trace_count: number;
            /** Llm Call Count */
            llm_call_count: number;
            /** Graph Query Count */
            graph_query_count: number;
            /** Total Tokens */
            total_tokens: number;
            /** Total Cost Micro Usd */
            total_cost_micro_usd: number;
            /** P50 Duration Ms */
            p50_duration_ms: number;
            /** P95 Duration Ms */
            p95_duration_ms: number;
        };
        /**
         * TraceSummary
         * @description One request's worth of spans, rolled up for the traces list.
         */
        TraceSummary: {
            /** Trace Id */
            trace_id: string;
            /** Name */
            name: string;
            /** Route */
            route: string | null;
            /** Agent Name */
            agent_name: string | null;
            /** Member Id */
            member_id: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number;
            status: components["schemas"]["SpanStatus"];
            /** Span Count */
            span_count: number;
            /** Llm Count */
            llm_count: number;
            /** Tool Count */
            tool_count: number;
            /** Db Count */
            db_count: number;
            /** Error Count */
            error_count: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Micro Usd */
            cost_micro_usd: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkoutPlan
         * @description The typed response of ``POST /api/workout`` (doubles as the schema).
         */
        WorkoutPlan: {
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            warmup: components["schemas"]["PlanSection"];
            main: components["schemas"]["PlanSection"];
            cooldown: components["schemas"]["PlanSection"];
            /** Time Window Minutes */
            time_window_minutes: number;
            /** Estimated Duration Minutes */
            estimated_duration_minutes: number;
            /** Filtered Out For Safety */
            filtered_out_for_safety: components["schemas"]["ExcludedExercise"][];
            /** Other Exclusions */
            other_exclusions: components["schemas"]["ExcludedExercise"][];
            constraints_used: components["schemas"]["ConstraintSet"];
            /** Resolution Notes */
            resolution_notes: string[];
            /** Pool Size */
            pool_size: number;
        };
        /**
         * WorkoutRequest
         * @description Input to ``POST /api/workout``.
         */
        WorkoutRequest: {
            /** Member Id */
            member_id: string;
            /** Prompt */
            prompt: string;
            /** Time Window Minutes */
            time_window_minutes: number;
            prior_constraints?: components["schemas"]["ConstraintSet"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_member_api_members__member_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_workout_api_workout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    member_context_slice_api_members__member_id__context_get: {
        parameters: {
            query?: {
                sections?: ("profile" | "goals" | "adherence" | "biomarkers" | "weight_trend" | "labs" | "workout_history" | "chat_history" | "coach_brief" | "injuries" | "equipment")[];
            };
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextSlice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilot_run_api_copilot__member_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_api_traces_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Keep only successful or only failed traces. */
                status?: components["schemas"]["SpanStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trace_stats_api_traces_stats_get: {
        parameters: {
            query?: {
                window_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
